// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.7
// source: github.com/infobloxopen/protoc-gen-atlas-validate/options/atlas_validate.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AtlasValidateFieldOption_Operation int32

const (
	//Field allow only on create operation
	AtlasValidateFieldOption_create AtlasValidateFieldOption_Operation = 0
	//Field allow only on update operation
	AtlasValidateFieldOption_update AtlasValidateFieldOption_Operation = 1
	//Field allow only on replace operation
	AtlasValidateFieldOption_replace AtlasValidateFieldOption_Operation = 2
)

// Enum value maps for AtlasValidateFieldOption_Operation.
var (
	AtlasValidateFieldOption_Operation_name = map[int32]string{
		0: "create",
		1: "update",
		2: "replace",
	}
	AtlasValidateFieldOption_Operation_value = map[string]int32{
		"create":  0,
		"update":  1,
		"replace": 2,
	}
)

func (x AtlasValidateFieldOption_Operation) Enum() *AtlasValidateFieldOption_Operation {
	p := new(AtlasValidateFieldOption_Operation)
	*p = x
	return p
}

func (x AtlasValidateFieldOption_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AtlasValidateFieldOption_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_enumTypes[0].Descriptor()
}

func (AtlasValidateFieldOption_Operation) Type() protoreflect.EnumType {
	return &file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_enumTypes[0]
}

func (x AtlasValidateFieldOption_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AtlasValidateFieldOption_Operation.Descriptor instead.
func (AtlasValidateFieldOption_Operation) EnumDescriptor() ([]byte, []int) {
	return file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_rawDescGZIP(), []int{3, 0}
}

type AtlasValidateFileOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllowUnknownFields bool `protobuf:"varint,1,opt,name=allow_unknown_fields,json=allowUnknownFields,proto3" json:"allow_unknown_fields,omitempty"`
}

func (x *AtlasValidateFileOption) Reset() {
	*x = AtlasValidateFileOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AtlasValidateFileOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtlasValidateFileOption) ProtoMessage() {}

func (x *AtlasValidateFileOption) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtlasValidateFileOption.ProtoReflect.Descriptor instead.
func (*AtlasValidateFileOption) Descriptor() ([]byte, []int) {
	return file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_rawDescGZIP(), []int{0}
}

func (x *AtlasValidateFileOption) GetAllowUnknownFields() bool {
	if x != nil {
		return x.AllowUnknownFields
	}
	return false
}

type AtlasValidateMethodOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllowUnknownFields bool `protobuf:"varint,1,opt,name=allow_unknown_fields,json=allowUnknownFields,proto3" json:"allow_unknown_fields,omitempty"`
}

func (x *AtlasValidateMethodOption) Reset() {
	*x = AtlasValidateMethodOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AtlasValidateMethodOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtlasValidateMethodOption) ProtoMessage() {}

func (x *AtlasValidateMethodOption) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtlasValidateMethodOption.ProtoReflect.Descriptor instead.
func (*AtlasValidateMethodOption) Descriptor() ([]byte, []int) {
	return file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_rawDescGZIP(), []int{1}
}

func (x *AtlasValidateMethodOption) GetAllowUnknownFields() bool {
	if x != nil {
		return x.AllowUnknownFields
	}
	return false
}

type AtlasValidateServiceOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllowUnknownFields bool `protobuf:"varint,1,opt,name=allow_unknown_fields,json=allowUnknownFields,proto3" json:"allow_unknown_fields,omitempty"`
}

func (x *AtlasValidateServiceOption) Reset() {
	*x = AtlasValidateServiceOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AtlasValidateServiceOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtlasValidateServiceOption) ProtoMessage() {}

func (x *AtlasValidateServiceOption) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtlasValidateServiceOption.ProtoReflect.Descriptor instead.
func (*AtlasValidateServiceOption) Descriptor() ([]byte, []int) {
	return file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_rawDescGZIP(), []int{2}
}

func (x *AtlasValidateServiceOption) GetAllowUnknownFields() bool {
	if x != nil {
		return x.AllowUnknownFields
	}
	return false
}

type AtlasValidateFieldOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deny     []AtlasValidateFieldOption_Operation `protobuf:"varint,1,rep,packed,name=deny,proto3,enum=atlas_validate.AtlasValidateFieldOption_Operation" json:"deny,omitempty"`
	Required []AtlasValidateFieldOption_Operation `protobuf:"varint,2,rep,packed,name=required,proto3,enum=atlas_validate.AtlasValidateFieldOption_Operation" json:"required,omitempty"`
}

func (x *AtlasValidateFieldOption) Reset() {
	*x = AtlasValidateFieldOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AtlasValidateFieldOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtlasValidateFieldOption) ProtoMessage() {}

func (x *AtlasValidateFieldOption) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtlasValidateFieldOption.ProtoReflect.Descriptor instead.
func (*AtlasValidateFieldOption) Descriptor() ([]byte, []int) {
	return file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_rawDescGZIP(), []int{3}
}

func (x *AtlasValidateFieldOption) GetDeny() []AtlasValidateFieldOption_Operation {
	if x != nil {
		return x.Deny
	}
	return nil
}

func (x *AtlasValidateFieldOption) GetRequired() []AtlasValidateFieldOption_Operation {
	if x != nil {
		return x.Required
	}
	return nil
}

var file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*AtlasValidateFileOption)(nil),
		Field:         52219,
		Name:          "atlas_validate.file",
		Tag:           "bytes,52219,opt,name=file",
		Filename:      "github.com/infobloxopen/protoc-gen-atlas-validate/options/atlas_validate.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*AtlasValidateMethodOption)(nil),
		Field:         52219,
		Name:          "atlas_validate.method",
		Tag:           "bytes,52219,opt,name=method",
		Filename:      "github.com/infobloxopen/protoc-gen-atlas-validate/options/atlas_validate.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*AtlasValidateServiceOption)(nil),
		Field:         52219,
		Name:          "atlas_validate.service",
		Tag:           "bytes,52219,opt,name=service",
		Filename:      "github.com/infobloxopen/protoc-gen-atlas-validate/options/atlas_validate.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*AtlasValidateFieldOption)(nil),
		Field:         52219,
		Name:          "atlas_validate.field",
		Tag:           "bytes,52219,opt,name=field",
		Filename:      "github.com/infobloxopen/protoc-gen-atlas-validate/options/atlas_validate.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional atlas_validate.AtlasValidateFileOption file = 52219;
	E_File = &file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional atlas_validate.AtlasValidateMethodOption method = 52219;
	E_Method = &file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_extTypes[1]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional atlas_validate.AtlasValidateServiceOption service = 52219;
	E_Service = &file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_extTypes[2]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional atlas_validate.AtlasValidateFieldOption field = 52219;
	E_Field = &file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_extTypes[3]
)

var File_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto protoreflect.FileDescriptor

var file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_rawDesc = []byte{
	0x0a, 0x4e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6e, 0x66,
	0x6f, 0x62, 0x6c, 0x6f, 0x78, 0x6f, 0x70, 0x65, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x2d, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x74, 0x6c, 0x61,
	0x73, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0e, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x17, 0x41, 0x74, 0x6c, 0x61, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a,
	0x14, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x61, 0x6c, 0x6c,
	0x6f, 0x77, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22,
	0x4d, 0x0a, 0x19, 0x41, 0x74, 0x6c, 0x61, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x14,
	0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x61, 0x6c, 0x6c, 0x6f,
	0x77, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x4e,
	0x0a, 0x1a, 0x41, 0x74, 0x6c, 0x61, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x14,
	0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x61, 0x6c, 0x6c, 0x6f,
	0x77, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0xe4,
	0x01, 0x0a, 0x18, 0x41, 0x74, 0x6c, 0x61, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x46, 0x0a, 0x04, 0x64,
	0x65, 0x6e, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x32, 0x2e, 0x61, 0x74, 0x6c, 0x61,
	0x73, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x41, 0x74, 0x6c, 0x61, 0x73,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x64,
	0x65, 0x6e, 0x79, 0x12, 0x4e, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x32, 0x2e, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x5f, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x41, 0x74, 0x6c, 0x61, 0x73, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x64, 0x22, 0x30, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x0a, 0x0a, 0x06, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x10, 0x02, 0x3a, 0x5b, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x1c, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xfb, 0x97, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2e, 0x41, 0x74, 0x6c, 0x61, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x66, 0x69,
	0x6c, 0x65, 0x3a, 0x63, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x1e, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xfb, 0x97, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x5f, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x41, 0x74, 0x6c, 0x61, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x3a, 0x67, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0xfb, 0x97, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x61, 0x74,
	0x6c, 0x61, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x41, 0x74, 0x6c,
	0x61, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x3a, 0x5f, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xfb, 0x97, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x28, 0x2e, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2e, 0x41, 0x74, 0x6c, 0x61, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x69, 0x6e, 0x66, 0x6f, 0x62, 0x6c, 0x6f, 0x78, 0x6f, 0x70, 0x65, 0x6e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x2d, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x3b, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_rawDescOnce sync.Once
	file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_rawDescData = file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_rawDesc
)

func file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_rawDescGZIP() []byte {
	file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_rawDescOnce.Do(func() {
		file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_rawDescData)
	})
	return file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_rawDescData
}

var file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_goTypes = []interface{}{
	(AtlasValidateFieldOption_Operation)(0), // 0: atlas_validate.AtlasValidateFieldOption.Operation
	(*AtlasValidateFileOption)(nil),         // 1: atlas_validate.AtlasValidateFileOption
	(*AtlasValidateMethodOption)(nil),       // 2: atlas_validate.AtlasValidateMethodOption
	(*AtlasValidateServiceOption)(nil),      // 3: atlas_validate.AtlasValidateServiceOption
	(*AtlasValidateFieldOption)(nil),        // 4: atlas_validate.AtlasValidateFieldOption
	(*descriptorpb.FileOptions)(nil),        // 5: google.protobuf.FileOptions
	(*descriptorpb.MethodOptions)(nil),      // 6: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil),     // 7: google.protobuf.ServiceOptions
	(*descriptorpb.FieldOptions)(nil),       // 8: google.protobuf.FieldOptions
}
var file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_depIdxs = []int32{
	0,  // 0: atlas_validate.AtlasValidateFieldOption.deny:type_name -> atlas_validate.AtlasValidateFieldOption.Operation
	0,  // 1: atlas_validate.AtlasValidateFieldOption.required:type_name -> atlas_validate.AtlasValidateFieldOption.Operation
	5,  // 2: atlas_validate.file:extendee -> google.protobuf.FileOptions
	6,  // 3: atlas_validate.method:extendee -> google.protobuf.MethodOptions
	7,  // 4: atlas_validate.service:extendee -> google.protobuf.ServiceOptions
	8,  // 5: atlas_validate.field:extendee -> google.protobuf.FieldOptions
	1,  // 6: atlas_validate.file:type_name -> atlas_validate.AtlasValidateFileOption
	2,  // 7: atlas_validate.method:type_name -> atlas_validate.AtlasValidateMethodOption
	3,  // 8: atlas_validate.service:type_name -> atlas_validate.AtlasValidateServiceOption
	4,  // 9: atlas_validate.field:type_name -> atlas_validate.AtlasValidateFieldOption
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	6,  // [6:10] is the sub-list for extension type_name
	2,  // [2:6] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() {
	file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_init()
}
func file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_init() {
	if File_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AtlasValidateFileOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AtlasValidateMethodOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AtlasValidateServiceOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AtlasValidateFieldOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_goTypes,
		DependencyIndexes: file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_depIdxs,
		EnumInfos:         file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_enumTypes,
		MessageInfos:      file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_msgTypes,
		ExtensionInfos:    file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_extTypes,
	}.Build()
	File_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto = out.File
	file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_rawDesc = nil
	file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_goTypes = nil
	file_github_com_infobloxopen_protoc_gen_atlas_validate_options_atlas_validate_proto_depIdxs = nil
}
