// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/askurydzin/protoc-gen-atlas-validate/options/atlas_validate.proto

/*
Package options is a generated protocol buffer package.

It is generated from these files:
	github.com/askurydzin/protoc-gen-atlas-validate/options/atlas_validate.proto

It has these top-level messages:
	AtlasValidateFileOption
	AtlasValidateMethodOption
	AtlasValidateServiceOption
*/
package options

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type AtlasValidateFileOption struct {
	AllowUnknownFields *bool  `protobuf:"varint,1,opt,name=allow_unknown_fields,json=allowUnknownFields" json:"allow_unknown_fields,omitempty"`
	XXX_unrecognized   []byte `json:"-"`
}

func (m *AtlasValidateFileOption) Reset()         { *m = AtlasValidateFileOption{} }
func (m *AtlasValidateFileOption) String() string { return proto.CompactTextString(m) }
func (*AtlasValidateFileOption) ProtoMessage()    {}
func (*AtlasValidateFileOption) Descriptor() ([]byte, []int) {
	return fileDescriptorAtlasValidate, []int{0}
}

func (m *AtlasValidateFileOption) GetAllowUnknownFields() bool {
	if m != nil && m.AllowUnknownFields != nil {
		return *m.AllowUnknownFields
	}
	return false
}

type AtlasValidateMethodOption struct {
	AllowUnknownFields *bool  `protobuf:"varint,1,opt,name=allow_unknown_fields,json=allowUnknownFields" json:"allow_unknown_fields,omitempty"`
	XXX_unrecognized   []byte `json:"-"`
}

func (m *AtlasValidateMethodOption) Reset()         { *m = AtlasValidateMethodOption{} }
func (m *AtlasValidateMethodOption) String() string { return proto.CompactTextString(m) }
func (*AtlasValidateMethodOption) ProtoMessage()    {}
func (*AtlasValidateMethodOption) Descriptor() ([]byte, []int) {
	return fileDescriptorAtlasValidate, []int{1}
}

func (m *AtlasValidateMethodOption) GetAllowUnknownFields() bool {
	if m != nil && m.AllowUnknownFields != nil {
		return *m.AllowUnknownFields
	}
	return false
}

type AtlasValidateServiceOption struct {
	AllowUnknownFields *bool  `protobuf:"varint,1,opt,name=allow_unknown_fields,json=allowUnknownFields" json:"allow_unknown_fields,omitempty"`
	XXX_unrecognized   []byte `json:"-"`
}

func (m *AtlasValidateServiceOption) Reset()         { *m = AtlasValidateServiceOption{} }
func (m *AtlasValidateServiceOption) String() string { return proto.CompactTextString(m) }
func (*AtlasValidateServiceOption) ProtoMessage()    {}
func (*AtlasValidateServiceOption) Descriptor() ([]byte, []int) {
	return fileDescriptorAtlasValidate, []int{2}
}

func (m *AtlasValidateServiceOption) GetAllowUnknownFields() bool {
	if m != nil && m.AllowUnknownFields != nil {
		return *m.AllowUnknownFields
	}
	return false
}

var E_File = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*AtlasValidateFileOption)(nil),
	Field:         52219,
	Name:          "atlas_validate.file",
	Tag:           "bytes,52219,opt,name=file",
	Filename:      "github.com/askurydzin/protoc-gen-atlas-validate/options/atlas_validate.proto",
}

var E_Method = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MethodOptions)(nil),
	ExtensionType: (*AtlasValidateMethodOption)(nil),
	Field:         52219,
	Name:          "atlas_validate.method",
	Tag:           "bytes,52219,opt,name=method",
	Filename:      "github.com/askurydzin/protoc-gen-atlas-validate/options/atlas_validate.proto",
}

var E_Service = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*AtlasValidateServiceOption)(nil),
	Field:         52219,
	Name:          "atlas_validate.service",
	Tag:           "bytes,52219,opt,name=service",
	Filename:      "github.com/askurydzin/protoc-gen-atlas-validate/options/atlas_validate.proto",
}

func init() {
	proto.RegisterType((*AtlasValidateFileOption)(nil), "atlas_validate.AtlasValidateFileOption")
	proto.RegisterType((*AtlasValidateMethodOption)(nil), "atlas_validate.AtlasValidateMethodOption")
	proto.RegisterType((*AtlasValidateServiceOption)(nil), "atlas_validate.AtlasValidateServiceOption")
	proto.RegisterExtension(E_File)
	proto.RegisterExtension(E_Method)
	proto.RegisterExtension(E_Service)
}

func init() {
	proto.RegisterFile("github.com/askurydzin/protoc-gen-atlas-validate/options/atlas_validate.proto", fileDescriptorAtlasValidate)
}

var fileDescriptorAtlasValidate = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x19, 0x8a, 0x4a, 0x04, 0x0f, 0x41, 0x70, 0x0e, 0xd1, 0xb2, 0x8b, 0x53, 0x68, 0x2a,
	0x1e, 0xeb, 0x41, 0xe6, 0x61, 0x17, 0x9d, 0x42, 0x45, 0x0f, 0x7a, 0x28, 0x59, 0x9b, 0x76, 0x61,
	0x59, 0x5e, 0x69, 0xd2, 0x0d, 0xfd, 0x22, 0x7e, 0x58, 0x2f, 0x62, 0xda, 0xd2, 0xc5, 0xe1, 0x0e,
	0x3d, 0x15, 0xde, 0xe3, 0xff, 0xfb, 0xf7, 0xfd, 0x08, 0x7a, 0x48, 0xb9, 0x9e, 0x16, 0x13, 0x12,
	0xc1, 0xdc, 0xa3, 0x6a, 0x56, 0xe4, 0x1f, 0xf1, 0x27, 0x97, 0x5e, 0x96, 0x83, 0x86, 0xc8, 0x4d,
	0x99, 0x74, 0xa9, 0x16, 0x54, 0xb9, 0x0b, 0x2a, 0x78, 0x4c, 0x35, 0xf3, 0x20, 0xd3, 0x1c, 0xa4,
	0xf2, 0xcc, 0x38, 0xac, 0xc7, 0xc4, 0x04, 0xf0, 0x81, 0x3d, 0xed, 0x39, 0x29, 0x40, 0x2a, 0x58,
	0x89, 0x9b, 0x14, 0x89, 0x17, 0x33, 0x15, 0xe5, 0x3c, 0xd3, 0x90, 0x97, 0x89, 0xfe, 0x3d, 0x3a,
	0x1a, 0xfe, 0x66, 0x5e, 0xab, 0xc8, 0x88, 0x0b, 0xf6, 0x64, 0x2a, 0xf0, 0x15, 0x3a, 0xa4, 0x42,
	0xc0, 0x32, 0x2c, 0xe4, 0x4c, 0xc2, 0x52, 0x86, 0x09, 0x67, 0x22, 0x56, 0xdd, 0x8e, 0xd3, 0x19,
	0xec, 0x05, 0xd8, 0xec, 0x5e, 0xca, 0xd5, 0xc8, 0x6c, 0xfa, 0x63, 0x74, 0x6c, 0xc1, 0xc6, 0x4c,
	0x4f, 0x21, 0x6e, 0x8d, 0x7b, 0x44, 0x3d, 0x0b, 0xf7, 0xcc, 0xf2, 0x05, 0x8f, 0x5a, 0xff, 0x9e,
	0xff, 0x8e, 0xb6, 0x13, 0x2e, 0x18, 0x3e, 0x21, 0xa5, 0x16, 0x52, 0x6b, 0x21, 0xcd, 0xd5, 0xaa,
	0xfb, 0xfd, 0xb5, 0xe5, 0x74, 0x06, 0xfb, 0xd7, 0xe7, 0xe4, 0x8f, 0xe2, 0x7f, 0x3c, 0x05, 0x06,
	0xea, 0x47, 0x68, 0x67, 0x6e, 0xce, 0xc5, 0xa7, 0x6b, 0xf8, 0x55, 0x0f, 0x4d, 0xc1, 0xc5, 0xc6,
	0x82, 0xd5, 0x4c, 0x50, 0xa1, 0xfd, 0x14, 0xed, 0xaa, 0x52, 0x02, 0x3e, 0x5b, 0x6b, 0xb1, 0xf4,
	0x34, 0x35, 0x97, 0x1b, 0x6b, 0xac, 0x50, 0x50, 0xd3, 0xef, 0x86, 0x6f, 0xb7, 0x2d, 0x1f, 0xe6,
	0x4d, 0xf5, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0x45, 0xc2, 0xdf, 0xf6, 0xda, 0x02, 0x00, 0x00,
}
