// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: examplepb/example_multi.proto

package examplepb

import (
	_ "github.com/infobloxopen/protoc-gen-atlas-validate/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *User2) Reset() {
	*x = User2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examplepb_example_multi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User2) ProtoMessage() {}

func (x *User2) ProtoReflect() protoreflect.Message {
	mi := &file_examplepb_example_multi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User2.ProtoReflect.Descriptor instead.
func (*User2) Descriptor() ([]byte, []int) {
	return file_examplepb_example_multi_proto_rawDescGZIP(), []int{0}
}

func (x *User2) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User2) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EmptyResponse2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyResponse2) Reset() {
	*x = EmptyResponse2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examplepb_example_multi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyResponse2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse2) ProtoMessage() {}

func (x *EmptyResponse2) ProtoReflect() protoreflect.Message {
	mi := &file_examplepb_example_multi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse2.ProtoReflect.Descriptor instead.
func (*EmptyResponse2) Descriptor() ([]byte, []int) {
	return file_examplepb_example_multi_proto_rawDescGZIP(), []int{1}
}

var File_examplepb_example_multi_proto protoreflect.FileDescriptor

var file_examplepb_example_multi_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x70, 0x62, 0x2f, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x5f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0c, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x66, 0x6f, 0x6f, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x61, 0x74, 0x6c,
	0x61, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x3f, 0x0a, 0x05, 0x55, 0x73, 0x65, 0x72, 0x32, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x07, 0xda, 0xbf, 0x19, 0x03, 0x0a, 0x01, 0x00, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x09, 0xda, 0xbf, 0x19, 0x05, 0x12, 0x03, 0x00, 0x02, 0x01, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0x32, 0x59, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x73, 0x32, 0x12, 0x4f,
	0x0a, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x32, 0x12, 0x13, 0x2e, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x73, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x32, 0x1a, 0x1c,
	0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x22, 0x11, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x0b, 0x3a, 0x01, 0x2a, 0x22, 0x06, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x42,
	0x4f, 0x5a, 0x4d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6e,
	0x66, 0x6f, 0x62, 0x6c, 0x6f, 0x78, 0x6f, 0x70, 0x65, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x2d, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x70, 0x62, 0x3b, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_examplepb_example_multi_proto_rawDescOnce sync.Once
	file_examplepb_example_multi_proto_rawDescData = file_examplepb_example_multi_proto_rawDesc
)

func file_examplepb_example_multi_proto_rawDescGZIP() []byte {
	file_examplepb_example_multi_proto_rawDescOnce.Do(func() {
		file_examplepb_example_multi_proto_rawDescData = protoimpl.X.CompressGZIP(file_examplepb_example_multi_proto_rawDescData)
	})
	return file_examplepb_example_multi_proto_rawDescData
}

var file_examplepb_example_multi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_examplepb_example_multi_proto_goTypes = []interface{}{
	(*User2)(nil),          // 0: examples.foo.User2
	(*EmptyResponse2)(nil), // 1: examples.foo.EmptyResponse2
}
var file_examplepb_example_multi_proto_depIdxs = []int32{
	0, // 0: examples.foo.Users2.Create2:input_type -> examples.foo.User2
	1, // 1: examples.foo.Users2.Create2:output_type -> examples.foo.EmptyResponse2
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examplepb_example_multi_proto_init() }
func file_examplepb_example_multi_proto_init() {
	if File_examplepb_example_multi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_examplepb_example_multi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_examplepb_example_multi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyResponse2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_examplepb_example_multi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examplepb_example_multi_proto_goTypes,
		DependencyIndexes: file_examplepb_example_multi_proto_depIdxs,
		MessageInfos:      file_examplepb_example_multi_proto_msgTypes,
	}.Build()
	File_examplepb_example_multi_proto = out.File
	file_examplepb_example_multi_proto_rawDesc = nil
	file_examplepb_example_multi_proto_goTypes = nil
	file_examplepb_example_multi_proto_depIdxs = nil
}
