// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/examplepb/example.proto

/*
Package examplepb is a generated protocol buffer package.

It is generated from these files:
	example/examplepb/example.proto
	example/examplepb/examplepb.proto
	example/examplepb/example_multi.proto

It has these top-level messages:
	User
	Address
	Group
	CreateUserRequest
	UpdateUserRequest
	EmptyRequest
	EmptyResponse
	Profile
	UpdateProfileRequest
	User2
	EmptyResponse2
*/
package examplepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"
import google_protobuf2 "github.com/golang/protobuf/ptypes/empty"
import google_protobuf3 "github.com/golang/protobuf/ptypes/any"
import google_protobuf4 "github.com/golang/protobuf/ptypes/wrappers"
import _ "github.com/infobloxopen/protoc-gen-atlas-validate/options"
import external "github.com/infobloxopen/protoc-gen-atlas-validate/example/external"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id           int32                       `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name         string                      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Profile      *Profile                    `protobuf:"bytes,3,opt,name=profile" json:"profile,omitempty"`
	Address      *Address                    `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
	Groups       []*Group                    `protobuf:"bytes,5,rep,name=groups" json:"groups,omitempty"`
	Parents      []*User_Parent              `protobuf:"bytes,6,rep,name=parents" json:"parents,omitempty"`
	ExternalUser *external.ExternalUser      `protobuf:"bytes,7,opt,name=external_user,json=externalUser" json:"external_user,omitempty"`
	EmptyList    []*google_protobuf2.Empty   `protobuf:"bytes,8,rep,name=empty_list,json=emptyList" json:"empty_list,omitempty"`
	Timestamp    *google_protobuf1.Timestamp `protobuf:"bytes,9,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *User) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *User) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *User) GetParents() []*User_Parent {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *User) GetExternalUser() *external.ExternalUser {
	if m != nil {
		return m.ExternalUser
	}
	return nil
}

func (m *User) GetEmptyList() []*google_protobuf2.Empty {
	if m != nil {
		return m.EmptyList
	}
	return nil
}

func (m *User) GetTimestamp() *google_protobuf1.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type User_Parent struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *User_Parent) Reset()                    { *m = User_Parent{} }
func (m *User_Parent) String() string            { return proto.CompactTextString(m) }
func (*User_Parent) ProtoMessage()               {}
func (*User_Parent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *User_Parent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Address struct {
	Country string            `protobuf:"bytes,1,opt,name=country" json:"country,omitempty"`
	State   string            `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	City    string            `protobuf:"bytes,3,opt,name=city" json:"city,omitempty"`
	Zip     string            `protobuf:"bytes,4,opt,name=zip" json:"zip,omitempty"`
	Tags    map[string]string `protobuf:"bytes,10,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *Address) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Group struct {
	Id    int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Notes string `protobuf:"bytes,3,opt,name=notes" json:"notes,omitempty"`
}

func (m *Group) Reset()                    { *m = Group{} }
func (m *Group) String() string            { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()               {}
func (*Group) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Group) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

type CreateUserRequest struct {
	Payload *User `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateUserRequest) GetPayload() *User {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateUserRequest struct {
	Payload *User `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
}

func (m *UpdateUserRequest) Reset()                    { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()               {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateUserRequest) GetPayload() *User {
	if m != nil {
		return m.Payload
	}
	return nil
}

type EmptyRequest struct {
}

func (m *EmptyRequest) Reset()                    { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string            { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()               {}
func (*EmptyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type EmptyResponse struct {
}

func (m *EmptyResponse) Reset()                    { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string            { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()               {}
func (*EmptyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type Profile struct {
	Id    int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Notes string `protobuf:"bytes,3,opt,name=notes" json:"notes,omitempty"`
}

func (m *Profile) Reset()                    { *m = Profile{} }
func (m *Profile) String() string            { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()               {}
func (*Profile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Profile) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

type UpdateProfileRequest struct {
	Payload *Profile `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
}

func (m *UpdateProfileRequest) Reset()                    { *m = UpdateProfileRequest{} }
func (m *UpdateProfileRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateProfileRequest) ProtoMessage()               {}
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateProfileRequest) GetPayload() *Profile {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "examplepb.User")
	proto.RegisterType((*User_Parent)(nil), "examplepb.User.Parent")
	proto.RegisterType((*Address)(nil), "examplepb.Address")
	proto.RegisterType((*Group)(nil), "examplepb.Group")
	proto.RegisterType((*CreateUserRequest)(nil), "examplepb.CreateUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "examplepb.UpdateUserRequest")
	proto.RegisterType((*EmptyRequest)(nil), "examplepb.EmptyRequest")
	proto.RegisterType((*EmptyResponse)(nil), "examplepb.EmptyResponse")
	proto.RegisterType((*Profile)(nil), "examplepb.Profile")
	proto.RegisterType((*UpdateProfileRequest)(nil), "examplepb.UpdateProfileRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Users service

type UsersClient interface {
	Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	Update(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	List(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	UpdateExternalUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*EmptyResponse, error)
	UpdateExternalUser2(ctx context.Context, in *external.ExternalUser, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/examplepb.Users/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Update(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/examplepb.Users/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) List(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/examplepb.Users/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UpdateExternalUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/examplepb.Users/UpdateExternalUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UpdateExternalUser2(ctx context.Context, in *external.ExternalUser, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/examplepb.Users/UpdateExternalUser2", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Users service

type UsersServer interface {
	Create(context.Context, *CreateUserRequest) (*EmptyResponse, error)
	Update(context.Context, *UpdateUserRequest) (*EmptyResponse, error)
	List(context.Context, *EmptyRequest) (*EmptyResponse, error)
	UpdateExternalUser(context.Context, *User) (*EmptyResponse, error)
	UpdateExternalUser2(context.Context, *external.ExternalUser) (*EmptyResponse, error)
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/examplepb.Users/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Create(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/examplepb.Users/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Update(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/examplepb.Users/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).List(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UpdateExternalUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UpdateExternalUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/examplepb.Users/UpdateExternalUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UpdateExternalUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UpdateExternalUser2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(external.ExternalUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UpdateExternalUser2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/examplepb.Users/UpdateExternalUser2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UpdateExternalUser2(ctx, req.(*external.ExternalUser))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "examplepb.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Users_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Users_Update_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Users_List_Handler,
		},
		{
			MethodName: "UpdateExternalUser",
			Handler:    _Users_UpdateExternalUser_Handler,
		},
		{
			MethodName: "UpdateExternalUser2",
			Handler:    _Users_UpdateExternalUser2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/examplepb/example.proto",
}

// Client API for Profiles service

type ProfilesClient interface {
	Create(ctx context.Context, in *Profile, opts ...grpc.CallOption) (*EmptyResponse, error)
	Update(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type profilesClient struct {
	cc *grpc.ClientConn
}

func NewProfilesClient(cc *grpc.ClientConn) ProfilesClient {
	return &profilesClient{cc}
}

func (c *profilesClient) Create(ctx context.Context, in *Profile, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/examplepb.Profiles/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesClient) Update(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/examplepb.Profiles/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Profiles service

type ProfilesServer interface {
	Create(context.Context, *Profile) (*EmptyResponse, error)
	Update(context.Context, *UpdateProfileRequest) (*EmptyResponse, error)
}

func RegisterProfilesServer(s *grpc.Server, srv ProfilesServer) {
	s.RegisterService(&_Profiles_serviceDesc, srv)
}

func _Profiles_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Profile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/examplepb.Profiles/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServer).Create(ctx, req.(*Profile))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profiles_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/examplepb.Profiles/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServer).Update(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Profiles_serviceDesc = grpc.ServiceDesc{
	ServiceName: "examplepb.Profiles",
	HandlerType: (*ProfilesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Profiles_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Profiles_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/examplepb/example.proto",
}

// Client API for Groups service

type GroupsClient interface {
	Create(ctx context.Context, in *Group, opts ...grpc.CallOption) (*EmptyResponse, error)
	Update(ctx context.Context, in *Group, opts ...grpc.CallOption) (*EmptyResponse, error)
	ValidatedList(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	ValidateWKT(ctx context.Context, in *google_protobuf3.Any, opts ...grpc.CallOption) (*google_protobuf4.DoubleValue, error)
}

type groupsClient struct {
	cc *grpc.ClientConn
}

func NewGroupsClient(cc *grpc.ClientConn) GroupsClient {
	return &groupsClient{cc}
}

func (c *groupsClient) Create(ctx context.Context, in *Group, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/examplepb.Groups/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) Update(ctx context.Context, in *Group, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/examplepb.Groups/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) ValidatedList(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/examplepb.Groups/ValidatedList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) ValidateWKT(ctx context.Context, in *google_protobuf3.Any, opts ...grpc.CallOption) (*google_protobuf4.DoubleValue, error) {
	out := new(google_protobuf4.DoubleValue)
	err := grpc.Invoke(ctx, "/examplepb.Groups/ValidateWKT", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Groups service

type GroupsServer interface {
	Create(context.Context, *Group) (*EmptyResponse, error)
	Update(context.Context, *Group) (*EmptyResponse, error)
	ValidatedList(context.Context, *EmptyRequest) (*EmptyResponse, error)
	ValidateWKT(context.Context, *google_protobuf3.Any) (*google_protobuf4.DoubleValue, error)
}

func RegisterGroupsServer(s *grpc.Server, srv GroupsServer) {
	s.RegisterService(&_Groups_serviceDesc, srv)
}

func _Groups_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Group)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/examplepb.Groups/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).Create(ctx, req.(*Group))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Group)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/examplepb.Groups/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).Update(ctx, req.(*Group))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_ValidatedList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).ValidatedList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/examplepb.Groups/ValidatedList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).ValidatedList(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_ValidateWKT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf3.Any)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).ValidateWKT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/examplepb.Groups/ValidateWKT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).ValidateWKT(ctx, req.(*google_protobuf3.Any))
	}
	return interceptor(ctx, in, info, handler)
}

var _Groups_serviceDesc = grpc.ServiceDesc{
	ServiceName: "examplepb.Groups",
	HandlerType: (*GroupsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Groups_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Groups_Update_Handler,
		},
		{
			MethodName: "ValidatedList",
			Handler:    _Groups_ValidatedList_Handler,
		},
		{
			MethodName: "ValidateWKT",
			Handler:    _Groups_ValidateWKT_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/examplepb/example.proto",
}

func init() { proto.RegisterFile("example/examplepb/example.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1043 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x4d, 0x6f, 0x1b, 0x45,
	0x18, 0xce, 0xae, 0xbf, 0xb2, 0xe3, 0x7c, 0xbe, 0xb1, 0xd2, 0xcd, 0xd6, 0x25, 0xee, 0x0a, 0x81,
	0xb1, 0x1a, 0x6f, 0xe5, 0x0a, 0x51, 0xb9, 0x02, 0xa9, 0x69, 0xa3, 0x22, 0xd1, 0xa0, 0xb2, 0x24,
	0x45, 0x58, 0x48, 0xd6, 0x38, 0x3b, 0x71, 0x96, 0xae, 0x77, 0x97, 0x9d, 0x71, 0x5a, 0x53, 0x71,
	0x41, 0xe2, 0xc4, 0x91, 0x33, 0xbf, 0x25, 0xe2, 0xce, 0x0d, 0x71, 0xc9, 0x99, 0x1f, 0x82, 0xe6,
	0x63, 0x37, 0xb6, 0x37, 0xb8, 0x6a, 0x39, 0xed, 0xcc, 0xbc, 0xcf, 0xbc, 0xcf, 0xfb, 0xf1, 0xcc,
	0xcc, 0xa2, 0x5d, 0xf2, 0x0a, 0x8f, 0xe2, 0x80, 0x38, 0xea, 0x1b, 0x0f, 0xd2, 0x51, 0x3b, 0x4e,
	0x22, 0x16, 0x81, 0x91, 0x19, 0xac, 0xfa, 0x30, 0x8a, 0x86, 0x01, 0x71, 0x70, 0xec, 0x3b, 0x38,
	0x0c, 0x23, 0x86, 0x99, 0x1f, 0x85, 0x54, 0x02, 0xad, 0x5d, 0x65, 0x15, 0xb3, 0xc1, 0xf8, 0xd4,
	0x61, 0xfe, 0x88, 0x50, 0x86, 0x47, 0xb1, 0x02, 0xdc, 0x9c, 0x07, 0x90, 0x51, 0xcc, 0x26, 0xca,
	0xb8, 0x33, 0x6f, 0xc4, 0x61, 0x6a, 0x7a, 0x6f, 0xde, 0xf4, 0x32, 0xc1, 0x71, 0x4c, 0x92, 0x94,
	0xf8, 0xcb, 0xa1, 0xcf, 0xce, 0xc6, 0x83, 0xf6, 0x49, 0x34, 0x72, 0xfc, 0xf0, 0x34, 0x1a, 0x04,
	0xd1, 0xab, 0x28, 0x26, 0xa1, 0xdc, 0x70, 0xb2, 0x37, 0x24, 0xe1, 0x1e, 0x66, 0x01, 0xa6, 0x7b,
	0xe7, 0x38, 0xf0, 0x3d, 0xcc, 0x88, 0x13, 0xc5, 0x22, 0x72, 0x47, 0x2c, 0xf7, 0xd3, 0x65, 0xe5,
	0xef, 0xab, 0xb7, 0xf7, 0x77, 0x55, 0x44, 0x46, 0x92, 0x10, 0x07, 0xd9, 0x40, 0xba, 0xb4, 0xff,
	0x28, 0xa0, 0xe2, 0x31, 0x25, 0x09, 0x6c, 0x23, 0xdd, 0xf7, 0x4c, 0xad, 0xa1, 0x35, 0x4b, 0xfb,
	0xe5, 0xcb, 0x8b, 0x1d, 0x7d, 0x79, 0xc9, 0xd5, 0x7d, 0x0f, 0x6e, 0xa1, 0x62, 0x88, 0x47, 0xc4,
	0xd4, 0x1b, 0x5a, 0xd3, 0xd8, 0x37, 0x2e, 0x2f, 0x76, 0x4a, 0x50, 0x58, 0xd2, 0x35, 0x57, 0x2c,
	0xc3, 0x1d, 0x54, 0x89, 0x93, 0xe8, 0xd4, 0x0f, 0x88, 0x59, 0x68, 0x68, 0xcd, 0x6a, 0x07, 0xda,
	0x59, 0x5b, 0xda, 0xcf, 0xa4, 0xc5, 0x4d, 0x21, 0x1c, 0x8d, 0x3d, 0x2f, 0x21, 0x94, 0x9a, 0xc5,
	0x1c, 0xfa, 0xa1, 0xb4, 0xb8, 0x29, 0x04, 0x9a, 0xa8, 0x3c, 0x4c, 0xa2, 0x71, 0x4c, 0xcd, 0x52,
	0xa3, 0xd0, 0xac, 0x76, 0x36, 0xa6, 0xc0, 0x4f, 0xb8, 0xc1, 0x55, 0x76, 0xb8, 0x8b, 0x2a, 0x31,
	0x4e, 0x48, 0xc8, 0xa8, 0x59, 0x16, 0xd0, 0xed, 0x29, 0x28, 0x4f, 0xaf, 0xfd, 0x4c, 0x98, 0xdd,
	0x14, 0x06, 0x0f, 0xd0, 0x6a, 0x5a, 0x89, 0xfe, 0x98, 0x92, 0xc4, 0xac, 0x88, 0x78, 0xf8, 0x3e,
	0x55, 0x9f, 0x03, 0x35, 0xe0, 0xdb, 0xdd, 0x15, 0x32, 0x35, 0x83, 0x8f, 0x11, 0x12, 0x0a, 0xe9,
	0x07, 0x3e, 0x65, 0xe6, 0xb2, 0x62, 0x94, 0x62, 0x68, 0xa7, 0x62, 0x68, 0x1f, 0x70, 0x88, 0x6b,
	0x08, 0xe4, 0x53, 0x9f, 0x32, 0xb8, 0x8f, 0x8c, 0x4c, 0x79, 0xa6, 0x21, 0xf8, 0xac, 0xdc, 0xae,
	0xa3, 0x14, 0xe1, 0x5e, 0x81, 0xad, 0x3a, 0x2a, 0xcb, 0x04, 0x00, 0x54, 0x3b, 0x78, 0xa3, 0x0c,
	0xd9, 0x03, 0xfb, 0x6f, 0x0d, 0x55, 0x54, 0xf1, 0xc0, 0x44, 0x95, 0x93, 0x68, 0x1c, 0xb2, 0x64,
	0xa2, 0x20, 0xe9, 0x14, 0x76, 0x51, 0x89, 0x32, 0xcc, 0x66, 0x3a, 0x89, 0x0a, 0x9a, 0xbe, 0xe4,
	0xca, 0x75, 0xee, 0xfa, 0xc4, 0x67, 0x13, 0xd1, 0x47, 0xc3, 0x15, 0x63, 0xd8, 0x40, 0x85, 0x1f,
	0xfd, 0x58, 0x34, 0xcb, 0x70, 0xf9, 0x10, 0xee, 0xa2, 0x22, 0xc3, 0x43, 0x6a, 0x22, 0x91, 0x75,
	0x3d, 0xdf, 0xbf, 0xf6, 0x11, 0x1e, 0xd2, 0x03, 0x4e, 0xe9, 0x0a, 0xa4, 0xf5, 0x09, 0x32, 0xb2,
	0x25, 0xee, 0xf0, 0x05, 0x49, 0x63, 0xe3, 0x43, 0xa8, 0xa1, 0xd2, 0x39, 0x0e, 0xc6, 0x2a, 0x2e,
	0x57, 0x4e, 0xba, 0xfa, 0x7d, 0xcd, 0xfe, 0x1a, 0x95, 0x44, 0x9b, 0xc1, 0x9c, 0xd2, 0xe6, 0xf2,
	0xe5, 0xc5, 0x4e, 0x11, 0x74, 0x4d, 0x17, 0xea, 0xb4, 0x66, 0xd4, 0x29, 0x74, 0xbb, 0xb1, 0xa4,
	0xa4, 0x59, 0x43, 0xa5, 0x30, 0x62, 0x84, 0xaa, 0x84, 0xe4, 0xc4, 0xfe, 0x0c, 0x6d, 0x3e, 0x4a,
	0x08, 0x66, 0x44, 0xf4, 0x95, 0xfc, 0x30, 0x26, 0x94, 0xc1, 0x47, 0x5c, 0x3f, 0x93, 0x20, 0xc2,
	0x92, 0xa5, 0xda, 0x59, 0x9f, 0xd3, 0x8f, 0x9b, 0xda, 0xf9, 0xfe, 0xe3, 0xd8, 0x7b, 0xf7, 0xfd,
	0x6b, 0x68, 0x45, 0x0a, 0x43, 0x6e, 0xb5, 0xd7, 0xd1, 0xaa, 0x9a, 0xd3, 0x38, 0x0a, 0x29, 0xb1,
	0x0f, 0x51, 0x45, 0x9d, 0x1b, 0x58, 0xbb, 0xca, 0x5b, 0x64, 0x5b, 0x9f, 0xc9, 0x56, 0x54, 0x02,
	0xf1, 0x4a, 0x2c, 0xca, 0xf7, 0x31, 0xaa, 0xc9, 0x78, 0xd3, 0xc3, 0xa8, 0x42, 0xbe, 0x33, 0x1f,
	0xf2, 0xf5, 0x07, 0x57, 0x42, 0x3a, 0xbf, 0x17, 0x51, 0x89, 0xe7, 0x41, 0xe1, 0x5b, 0x54, 0x96,
	0xf5, 0x83, 0xe9, 0xde, 0xe7, 0x4a, 0x6a, 0x99, 0x53, 0xd6, 0xd9, 0x04, 0x6f, 0xfc, 0xfc, 0xd7,
	0x3f, 0xbf, 0xe9, 0x9b, 0x76, 0xd9, 0xe1, 0x07, 0x8f, 0x76, 0x53, 0x12, 0xf8, 0x45, 0x43, 0x65,
	0x19, 0xeb, 0x8c, 0xef, 0x5c, 0xb9, 0x17, 0xf8, 0x7e, 0x24, 0x7c, 0x7f, 0x6a, 0x6d, 0x49, 0xdf,
	0xce, 0x6b, 0xe5, 0xbb, 0xed, 0x7b, 0x3f, 0x65, 0x44, 0xbd, 0x5b, 0x1d, 0x10, 0xf6, 0xeb, 0xcd,
	0xf0, 0x1d, 0x2a, 0x8a, 0xf3, 0x7a, 0x23, 0x4f, 0xf3, 0x26, 0xfe, 0xdb, 0x82, 0xff, 0x26, 0xa8,
	0xdc, 0x7a, 0x9b, 0xb0, 0xee, 0xe0, 0x90, 0x45, 0xec, 0x8c, 0x24, 0xe2, 0x9e, 0xa1, 0x30, 0x44,
	0x20, 0x33, 0x9a, 0xbe, 0x60, 0x60, 0x5e, 0x30, 0x0b, 0x38, 0x3e, 0x10, 0x1c, 0x0d, 0x6b, 0xdd,
	0x99, 0xb9, 0xc1, 0x68, 0x77, 0xf6, 0x46, 0x83, 0xef, 0xd1, 0x56, 0x9e, 0xa8, 0x03, 0xff, 0x71,
	0xc5, 0xbd, 0x39, 0x29, 0x6b, 0x7b, 0x8e, 0xb0, 0x3f, 0x16, 0xee, 0xbb, 0x5a, 0xab, 0xf3, 0xa7,
	0x86, 0x96, 0x95, 0x68, 0x28, 0x3c, 0xcd, 0x24, 0x72, 0x8d, 0xa6, 0x16, 0xf0, 0xd4, 0x04, 0xcf,
	0x9a, 0x6d, 0x38, 0xea, 0xbd, 0xa0, 0x5d, 0xad, 0x05, 0x49, 0x26, 0x8a, 0xdd, 0x9c, 0x28, 0x66,
	0x35, 0xbd, 0xc0, 0xf5, 0x9e, 0x78, 0xd1, 0x34, 0x41, 0x70, 0xdb, 0xda, 0xce, 0x08, 0xae, 0x57,
	0x40, 0xe7, 0xd7, 0x02, 0x2a, 0x3f, 0x91, 0x4f, 0xcb, 0xe7, 0x59, 0x32, 0xb9, 0xe7, 0x67, 0x01,
	0x1f, 0x08, 0xa6, 0x15, 0xbb, 0xe2, 0xc8, 0x17, 0x8a, 0x27, 0x72, 0x98, 0x25, 0xf2, 0x36, 0x9e,
	0xd4, 0x69, 0xb1, 0x56, 0x94, 0x27, 0xe7, 0x35, 0x8f, 0x54, 0x6b, 0xc1, 0x19, 0x5a, 0x7d, 0xae,
	0x5e, 0x79, 0xef, 0x5d, 0xe5, 0xfa, 0xbe, 0x7c, 0xe8, 0x05, 0x85, 0x09, 0x69, 0xb0, 0xbd, 0x55,
	0xa8, 0xaa, 0x61, 0x1f, 0x7b, 0x1e, 0x9c, 0xa3, 0x6a, 0xca, 0xf4, 0xcd, 0x17, 0x47, 0x50, 0xcb,
	0xbd, 0x59, 0x0f, 0xc3, 0x89, 0x55, 0xcf, 0xad, 0x3e, 0x8e, 0xc6, 0x83, 0x80, 0x3c, 0xe7, 0xd7,
	0xb9, 0x7d, 0x6f, 0x8a, 0xe8, 0x43, 0x6b, 0xd9, 0x79, 0xf9, 0x82, 0xf5, 0x87, 0x84, 0x75, 0xb5,
	0x56, 0xcf, 0xb4, 0xb6, 0xd2, 0x29, 0x67, 0xf3, 0xf9, 0xff, 0x0f, 0x0e, 0xba, 0x5a, 0xcb, 0x92,
	0xbf, 0x21, 0xda, 0xfe, 0xb1, 0xdc, 0xdc, 0x3b, 0xfc, 0x3f, 0xbf, 0x3f, 0xaa, 0x00, 0x0f, 0xb2,
	0xd1, 0xa0, 0x2c, 0xb6, 0xdd, 0xfb, 0x37, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xd4, 0x95, 0x9a, 0x69,
	0x0a, 0x00, 0x00,
}
